packages:
  - .

allowBuilds:
  electron-winstaller: true
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true

onlyBuiltDependencies:
  - electron-winstaller
  - esbuild
  - sharp
  - unrs-resolver
  - workerd
